export const products = [
  {
    id: 1,
    title: "T-shirt",
    price: 109.95,
    description: "Your perfect pack for everyday use and walks in the forest.",
    category: "men's clothing",
    image: "https://i.ibb.co/Tr238CV/shirt.jpg",
    rating: {
      rate: 3.9,
      count: 120,
    },
  },
  {
    id: 2,
    title: "Hoodie",
    price: 39.99,
    description: "Stay warm and stylish with our cozy hoodie.",
    category: "men's clothing",
    image: "https://i.ibb.co/Tr238CV/shirt.jpg",
    rating: {
      rate: 4.5,
      count: 80,
    },
  },
  {
    id: 3,
    title: "Jeans",
    price: 59.99,
    description: "Classic jeans for any occasion.",
    category: "men's clothing",
    image: "https://i.ibb.co/Tr238CV/shirt.jpg",
    rating: {
      rate: 4.2,
      count: 150,
    },
  },
  {
    id: 4,
    title: "Sneakers",
    price: 79.99,
    description: "Comfortable and stylish sneakers for everyday wear.",
    category: "men's shoes",
    image: "https://i.ibb.co/Tr238CV/shirt.jpg",
    rating: {
      rate: 4.8,
      count: 200,
    },
  },
  {
    id: 5,
    title: "Dress",
    price: 89.95,
    description: "Elegant dress for special occasions.",
    category: "women's clothing",
    image: "https://i.ibb.co/Tr238CV/shirt.jpg",
    rating: {
      rate: 4.6,
      count: 100,
    },
  },
  {
    id: 6,
    title: "Skirt",
    price: 49.99,
    description: "Versatile skirt that can be dressed up or down.",
    category: "women's clothing",
    image: "https://i.ibb.co/Tr238CV/shirt.jpg",
    rating: {
      rate: 4.3,
      count: 90,
    },
  },
  {
    id: 7,
    title: "Sandals",
    price: 29.99,
    description: "Casual sandals perfect for summer outings.",
    category: "women's shoes",
    image: "https://i.ibb.co/Tr238CV/shirt.jpg",
    rating: {
      rate: 4.0,
      count: 120,
    },
  },
  {
    id: 8,
    title: "Jacket",
    price: 129.99,
    description: "Stylish jacket to keep you warm in cold weather.",
    category: "men's clothing",
    image: "https://i.ibb.co/Tr238CV/shirt.jpg",
    rating: {
      rate: 4.4,
      count: 110,
    },
  },
  {
    id: 9,
    title: "Pants",
    price: 69.99,
    description: "Comfortable pants suitable for any occasion.",
    category: "men's clothing",
    image: "https://i.ibb.co/Tr238CV/shirt.jpg",
    rating: {
      rate: 4.1,
      count: 95,
    },
  },
  {
    id: 10,
    title: "Boots",
    price: 89.99,
    description: "Sturdy boots for outdoor adventures.",
    category: "men's shoes",
    image: "https://i.ibb.co/Tr238CV/shirt.jpg",
    rating: {
      rate: 4.7,
      count: 180,
    },
  },
  {
    id: 11,
    title: "Blouse",
    price: 49.95,
    description: "Chic blouse for a fashionable look.",
    category: "women's clothing",
    image: "https://i.ibb.co/Tr238CV/shirt.jpg",
    rating: {
      rate: 4.3,
      count: 85,
    },
  },
  {
    id: 12,
    title: "Sweater",
    price: 59.99,
    description: "Cozy sweater perfect for chilly evenings.",
    category: "women's clothing",
    image: "https://i.ibb.co/Tr238CV/shirt.jpg",
    rating: {
      rate: 4.6,
      count: 150,
    },
  },
  {
    id: 13,
    title: "Heels",
    price: 79.99,
    description: "Elegant heels to elevate your style.",
    category: "women's shoes",
    image: "https://i.ibb.co/Tr238CV/shirt.jpg",
    rating: {
      rate: 4.2,
      count: 100,
    },
  },
];
